source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/execs.conf
source = ~/.config/hypr/modules/default-software.conf
source = ~/.config/hypr/modules/envs.conf
source = ~/.config/hypr/modules/appearance.conf
source = ~/.config/hypr/modules/permission.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/workspaces.conf
source = ~/.config/hypr/modules/layerrules.conf
