preload = /home/ayunierto/.dotfiles/config/hypr/wallpapers/wallhaven-coffee-dark.jpg

wallpaper {
	monitor = eDP-1
	path = /home/ayunierto/.dotfiles/config/hypr/wallpapers/wallhaven-coffee-dark.jpg
	fit_mode = cover
}
