
##########################
####### LAYERRULES #######
##########################
# Blur rules for specific apps

layerrule {
    name = blur-swaync-control-center
    blur = on
    ignore_alpha = 0.5
    match:namespace = swaync-control-center
}

layerrule {
    name = ignorealpha-swaync-notification-window
    blur = on
    ignore_alpha = 0.5
    match:namespace = swaync-notification-window
}

layerrule {
    name = blur-wofi
    blur = on
    # ignore_alpha = 0.5
    match:namespace = wofi
}
