################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor= eDP-1,1920x1080@60,auto,1

# ############################
# # Monitor virtual HEADLESS #
# ############################
# # Crear monitor virtual al iniciar Hyprland
# exec-once = hyprctl output create headless
# # Configurar resolución del monitor virtual
# exec-once = hyprctl keyword monitor "HEADLESS-2,1366x768@60,auto,1"
# # Asignar workspace fijo al monitor virtual
# workspace = 4,monitor:HEADLESS-2

# # WayVNC autostart #
# exec-once = wayvnc --max-fps 30 -o HEADLESS-2 0.0.0.0
